function run
% Execute all tests for libode.
addpath('../problems');
addpath('../src');
addpath('../test_utils');

run_tests({
  @autonomize_problem_arc_test, ...
  @jacobian_test, ...
  @newton_test, ...
  @get_error_richardson_test, ...
  @erk1_test, ...
  @erk2_test, ...
  @erk4_test, ...
  @erk6_test, ...
  @cros_test, ...
  @cros4a_test, ...
  @cn_test, ...
  @bmp_test, ...
  @bork2_test, ...
  @bork3_test, ...
  @bork4_test, ...
  @oirk1_test, ...
  @oirk2_test, ...
  @oirk3_test, ...
  @oirk4_test, ...
  @mirk2a_test, ...
  @solveodet_test, ...
  @autonomize_performance_test, ...
  @solveodel_test, ...
  });
end
